// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6YP4U_pm0XuE0a3YFUCP_54KmbZfREGY',
    appId: '1:112537386830:android:45f3a05881f37f95bde81f',
    messagingSenderId: '112537386830',
    projectId: 'nexemble-tracker-dev',
    storageBucket: 'nexemble-tracker-dev.firebasestorage.app',
  );

  // TODO(firebase): STALE — these are Traccar's `traccar-client-app` values.
  // Regenerate for `nexemble-tracker-dev` (via `flutterfire configure`) once the
  // iOS app + APNs auth key are registered. Not used at runtime today: main()
  // calls Firebase.initializeApp() with no options, so iOS reads
  // ios/Runner/GoogleService-Info.plist (also still Traccar's — replace too).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEdxpKXTvJJfYDh28OLffAk4z7S7caf08',
    appId: '1:39016471396:ios:78cbbf5775b43308',
    messagingSenderId: '39016471396',
    projectId: 'traccar-client-app',
    databaseURL: 'https://traccar-client-app.firebaseio.com',
    storageBucket: 'traccar-client-app.firebasestorage.app',
    iosClientId: '39016471396-7mdutolor3h210bm9qmf60gp18lmmhnm.apps.googleusercontent.com',
    iosBundleId: 'org.traccar.client.TraccarClient',
  );

}