// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6YP4U_pm0XuE0a3YFUCP_54KmbZfREGY',
    appId: '1:112537386830:android:45f3a05881f37f95bde81f',
    messagingSenderId: '112537386830',
    projectId: 'nexemble-tracker-dev',
    storageBucket: 'nexemble-tracker-dev.firebasestorage.app',
  );

  // Kept in sync with ios/Runner/GoogleService-Info.plist (the runtime source
  // of truth — main() initializes without options). nexemble-tracker-dev; the
  // prod project's values land with the build-flavor split.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWeejWJ1mOq5qZe3JeXwTiAJBEskbfybw',
    appId: '1:112537386830:ios:decd056aa4a6f1e9bde81f',
    messagingSenderId: '112537386830',
    projectId: 'nexemble-tracker-dev',
    storageBucket: 'nexemble-tracker-dev.firebasestorage.app',
    iosBundleId: 'com.nexemble.nexapp',
  );

}